# Generated by Django 5.0.6 on 2025-03-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='achievement_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
