# Generated by Django 5.0.6 on 2024-11-28 04:27

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.ImageField(blank=True, default='/student_profile/default.jpg', null=True, upload_to='teacher_profile')),
                ('gender', models.CharField(max_length=19)),
                ('linkedin_id', models.URLField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructors',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile_number', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('is_changed_password', models.BooleanField(default=False)),
                ('profile_pic', models.ImageField(blank=True, default='/student_profile/default.jpg', null=True, upload_to='student_profile/')),
                ('linkedin_id', models.URLField(blank=True, null=True)),
                ('github_id', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
