# Generated by Django 5.2.5 on 2026-02-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fk_rewire_to_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'verbose_name': 'Administrator', 'verbose_name_plural': 'Administrators'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructors'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
