# Generated by Django 5.0.6 on 2024-11-05 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_scrummeeting_attendance'),
        ('student', '0016_remove_assignmentsubmission_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='scrum_meeting',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.DeleteModel(
            name='ScrumMeeting',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Roadmap',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
