# Generated by Django 5.0.6 on 2025-07-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flamesteam',
            name='project_description',
            field=models.TextField(blank=True, help_text='Description of the project', null=True),
        ),
        migrations.AddField(
            model_name='flamesteam',
            name='project_link',
            field=models.URLField(blank=True, help_text='Link to the project repository or demo', null=True),
        ),
        migrations.AddField(
            model_name='flamesteam',
            name='project_title',
            field=models.CharField(blank=True, help_text='Title of the project', max_length=200, null=True),
        ),
    ]
