# Generated by Django 5.2 on 2026-01-25 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlareRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="User's email address", max_length=254, unique=True, verbose_name='Email Address')),
                ('full_name', models.CharField(help_text="User's full name", max_length=200, verbose_name='Full Name')),
                ('phone_number', models.CharField(help_text="User's contact number", max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('occupation_status', models.CharField(choices=[('school_student', 'School Student'), ('undergrad_student', 'Undergraduation Student'), ('postgrad_student', 'Post Graduation Student'), ('working_professional', 'Working Professional'), ('not_working', 'Currently Not Working Anywhere')], help_text="User's current occupation/education status", max_length=50, verbose_name='Current Occupation Status')),
                ('current_year', models.CharField(blank=True, help_text='Applicable for students only', max_length=50, null=True, verbose_name='Current Year of Study')),
                ('courses_interested', models.TextField(help_text='JSON array of selected courses', verbose_name='Courses Interested In')),
                ('career_goals', models.TextField(help_text='JSON array of selected career goals', verbose_name='Career Goals')),
                ('motivation', models.TextField(help_text='What motivates the user to achieve their goals', verbose_name='Motivation')),
                ('commitment', models.BooleanField(default=False, help_text="User's commitment to the program", verbose_name='Ready to Commit')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the registration was created', verbose_name='Registration Date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the registration was last updated', verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'FLARE Registration',
                'verbose_name_plural': 'FLARE Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
