# Generated by Django 5.2.5 on 2026-01-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_flareregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the WhatsApp group (e.g., Python Masterclass)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Short description of the group", max_length=200
                    ),
                ),
                (
                    "whatsapp_link",
                    models.URLField(help_text="WhatsApp group invitation link"),
                ),
                (
                    "icon_class",
                    models.CharField(
                        default="fab fa-python",
                        help_text="Font Awesome icon class (e.g., fab fa-python, fas fa-code)",
                        max_length=50,
                    ),
                ),
                (
                    "icon_color",
                    models.CharField(
                        default="#ff6026",
                        help_text="Color for the icon (e.g., #ff6026)",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this group is currently active"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which groups are displayed (lower numbers first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "WhatsApp Group",
                "verbose_name_plural": "WhatsApp Groups",
                "ordering": ["display_order", "name"],
            },
        ),
    ]
