# Generated by Django 5.0.6 on 2025-04-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_flamesteam_flamesregistration_flamesteammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='discount_amount',
            field=models.IntegerField(default=499, help_text='Discount amount in percentage'),
        ),
    ]
