# Generated by Django 5.0.6 on 2025-07-07 09:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sitesettings'),
        ('home', '0002_flamesteam_project_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlamesScrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='This should be unique per team per day.')),
                ('what_done', models.TextField(verbose_name='What have you done so far?')),
                ('what_doing', models.TextField(verbose_name='What are you currently working on?')),
                ('any_issues', models.TextField(verbose_name="Any specific issues you're facing?")),
                ('something_more', models.TextField(blank=True, null=True, verbose_name="Anything else you'd like to share?")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.student')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrums', to='home.flamesteam')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('team', 'date')},
            },
        ),
    ]
