# Generated by Django 5.0.6 on 2025-04-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_flamesregistration_user_flamesteam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flamesregistration',
            name='college',
        ),
        migrations.RemoveField(
            model_name='flamesregistration',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='flamesregistration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='flamesregistration',
            name='full_name',
        ),
    ]
