# Generated by Django 5.2.5 on 2026-02-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_whatsappgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeClassWhatsappGroupLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(choices=[('Python', 'Python Free Class'), ('C', 'C Programming Free Class')], max_length=20, unique=True)),
                ('whatsapp_link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Free Class WhatsApp Group Link',
                'verbose_name_plural': 'Free Class WhatsApp Group Links',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='WhatsAppGroup',
        ),
    ]
