# Generated by Django 5.0.6 on 2025-04-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_referralcode_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flamesregistration',
            name='discounted_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='flamesregistration',
            name='original_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
