# Generated by Django 5.0.6 on 2024-11-05 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_question_remove_scholarshiptest_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='question',
        ),
        migrations.DeleteModel(
            name='ScholarshipTest',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='StudentSubmission',
        ),
    ]
