# Generated by Django 5.2.5 on 2026-02-19 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_freeclasswhatsappgrouplink_delete_whatsappgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='flamescourse',
            name='instructor',
            field=models.ManyToManyField(blank=True, related_name='flames_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flamesregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flames_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flamesteammember',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flames_team_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
