# Generated by Django 5.0.6 on 2025-04-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_flamesregistration_discounted_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flamesregistration',
            name='discounted_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flamesregistration',
            name='original_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
