# Generated by Django 5.0.6 on 2025-04-04 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresettoken'),
        ('home', '0004_remove_flamesregistration_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flamesregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flames_registrations', to='accounts.student'),
        ),
    ]
