# Generated by Django 5.0.6 on 2025-02-14 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='articles/thumbnails'),
            preserve_default=False,
        ),
    ]
