# Generated by Django 5.0.6 on 2025-04-04 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresettoken'),
        ('home', '0005_alter_flamesregistration_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flamesteammember',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='flamesteammember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='flamesteammember',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='flamesteammember',
            name='user',
        ),
        migrations.AddField(
            model_name='flamesteammember',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flames_team_memberships', to='accounts.student'),
        ),
    ]
