# Generated by Django 5.2.5 on 2026-03-30 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_fk_rewire_to_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlamesEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='e.g. 2025, 2026', unique=True)),
                ('name', models.CharField(help_text='e.g. "FLAMES 25"', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Only one edition should be active at a time.')),
                ('registration_open', models.BooleanField(default=False, help_text='Controls whether new registrations are accepted.')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Flames Edition',
                'verbose_name_plural': 'Flames Editions',
                'ordering': ['-year'],
            },
        ),
        migrations.AddField(
            model_name='flamescourse',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='home.flamesedition'),
        ),
        migrations.AddField(
            model_name='flamesregistration',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='home.flamesedition'),
        ),
        migrations.AddField(
            model_name='flamesteam',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='home.flamesedition'),
        ),
        migrations.AddField(
            model_name='referralcode',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_codes', to='home.flamesedition'),
        ),
    ]
