# Generated by Django 5.0.6 on 2025-04-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_flamesregistration_discounted_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flamesregistration',
            name='payable_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
