# Generated by Django 5.0.6 on 2025-02-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_article_created_at_article_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default='articles/thumbnails/default.jpg', upload_to='articles/thumbnails'),
        ),
    ]
