# Generated by Django 5.0.6 on 2025-05-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_flamescourse_whatsapp_group_link'),
    ]

    operations = [
       
    ]
