# Generated by Django 5.2.5 on 2026-03-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_enforce_edition_not_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flamescourse',
            options={'ordering': ['edition', 'title'], 'verbose_name': 'Flames Course', 'verbose_name_plural': 'Flames Courses'},
        ),
        migrations.RemoveField(
            model_name='flamescourse',
            name='roadmap',
        ),
        migrations.AlterField(
            model_name='flamescourse',
            name='button_color',
            field=models.CharField(blank=True, default='#ff6b00', help_text='Register button colour', max_length=50),
        ),
        migrations.AlterField(
            model_name='flamescourse',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='flamescourse',
            name='icon_class',
            field=models.CharField(blank=True, default='fas fa-fire', help_text='Font Awesome icon class (e.g. fas fa-layer-group)', max_length=100),
        ),
        migrations.AlterField(
            model_name='flamescourse',
            name='icon_color',
            field=models.CharField(blank=True, default='#ff6b00', help_text='Icon accent colour (hex or CSS value)', max_length=50),
        ),
        migrations.AlterField(
            model_name='flamescourse',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='flamescourse',
            name='what_you_will_learn',
            field=models.TextField(blank=True, default='', help_text='Enter each point on a new line'),
        ),
    ]
