# Generated by Django 5.0.6 on 2025-05-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_flamesregistration_payable_amount'),
    ]

    operations = [
       
    ]
