# Generated by Django 5.0.6 on 2025-05-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_flamesregistration_payable_amount'),
    ]

    operations = [
       
    ]
