# Generated by Django 5.0.6 on 2025-03-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlamesCourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='flames/instructors/')),
                ('expertise', models.CharField(max_length=200)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlamesCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('color', models.CharField(help_text='Color code like #ff6026', max_length=20)),
                ('what_you_will_learn', models.TextField(help_text='Enter points separated by new lines')),
                ('roadmap', models.TextField(help_text='Course roadmap details')),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='home.flamescourseinstructor')),
            ],
        ),
        migrations.CreateModel(
            name='FlamesCourseTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='flames/testimonials/')),
                ('content', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='home.flamescourse')),
            ],
        ),
        migrations.CreateModel(
            name='FlamesRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('college', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='home.flamescourse')),
            ],
        ),
    ]
