# Generated by Django 5.1.5 on 2025-06-13 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_flamesregistration_payable_amount'),
    ]

    operations = [
       
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('joining_link', models.URLField(help_text='Link to join the session')),
                ('recording_url', models.URLField(blank=True, help_text='URL to the session recording', null=True)),
                ('start_datetime', models.DateTimeField(help_text='Start date and time of the session')),
                ('end_datetime', models.DateTimeField(help_text='End date and time of the session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='home.flamescourse')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-start_datetime'],
            },
        ),
    ]
