# Generated by Django 5.2.5 on 2026-03-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_fix_flamescourse_mysql'),
    ]

    operations = [
        migrations.AddField(
            model_name='flamescourse',
            name='level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', help_text='Difficulty level shown on the course card', max_length=20),
        ),
        migrations.AlterField(
            model_name='flamescourse',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='flamescourse',
            name='what_you_will_learn',
            field=models.TextField(blank=True, default='', help_text='Enter each point on a new line', null=True),
        ),
    ]
