# Generated by Django 5.1.5 on 2025-06-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_flamesregistration_payable_amount_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='End date and time of the session', null=True),
        ),
    ]
