# Generated by Django 5.1.5 on 2025-06-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresettoken'),
        ('home', '0012_remove_session_date_and_more'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='flamescourse',
            name='instructor',
        ),
        migrations.AddField(
            model_name='flamescourse',
            name='instructor',
            field=models.ManyToManyField(blank=True, related_name='flames_courses', to='accounts.instructor'),
        ),
    ]
