# Generated by Django 5.0.6 on 2025-03-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_flamescourse_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flamescourse',
            old_name='color',
            new_name='icon_color',
        ),
        migrations.AddField(
            model_name='flamescourse',
            name='button_color',
            field=models.CharField(default=1, help_text='Color for the course button', max_length=200),
            preserve_default=False,
        ),
    ]
