# Generated by Django 5.2.4 on 2025-08-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='sheet_type',
            field=models.CharField(choices=[('Coding', 'Coding'), ('MCQ', 'MCQ')], default='Coding', max_length=20),
        ),
    ]
