# Generated by Django 5.0.6 on 2024-10-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheet',
            options={'verbose_name': 'Sheet', 'verbose_name_plural': 'Sheets'},
        ),
        migrations.AddField(
            model_name='sheet',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
