# Generated by Django 5.0.6 on 2024-11-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_question_cpu_time_limit_question_memory_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='cpu_time_limit',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
