# Generated by Django 5.0.6 on 2024-10-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
    ]
