# Generated by Django 5.0.6 on 2024-11-28 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_alter_question_cpu_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='language_id',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DriverCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.IntegerField(default=0)),
                ('code', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_codes', to='practice.question')),
            ],
        ),
    ]
