# Generated by Django 5.2.4 on 2025-08-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_mcqquestion_mcqsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqquestion',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
