# Generated by Django 5.0.6 on 2024-12-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_alter_solution_language_id_drivercode'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='drivercode',
            index=models.Index(fields=['question', 'language_id'], name='practice_dr_questio_dd3958_idx'),
        ),
    ]
