# Generated by Django 5.0.6 on 2024-12-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_drivercode_practice_dr_questio_dd3958_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
