# Generated by Django 5.2.4 on 2025-09-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_questionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='previous_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
