# Generated by Django 5.2.5 on 2026-02-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0006_add_previous_streak_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
