# Generated by Django 5.0.6 on 2024-10-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_streak_submission_testcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='sheet',
        ),
        migrations.AddField(
            model_name='question',
            name='sheets',
            field=models.ManyToManyField(blank=True, related_name='questions', to='practice.sheet'),
        ),
    ]
