# Generated by Django 5.2.5 on 2026-03-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0007_fk_rewire_to_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
