# Generated by Django 5.2.5 on 2026-03-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0008_batch_add_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='sheet_order',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
