# Generated by Django 5.0.6 on 2024-10-16 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0008_pod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pod',
            name='streak_active',
        ),
        migrations.AlterField(
            model_name='pod',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
