# Generated by Django 5.2.5 on 2026-03-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0009_batch_sheet_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='sheet_order',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
