# Generated by Django 5.0.6 on 2024-12-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0009_remove_question_link_sheet_custom_order_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='sheet',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
