# Generated by Django 5.2.5 on 2026-03-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0010_alter_batch_sheet_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='required_fields',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
