# Generated by Django 5.0.6 on 2024-12-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0010_remove_question_link_sheet_custom_order_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='sheet',
            name='is_sequential',
            field=models.BooleanField(default=False),
        ),
    ]
