# Generated by Django 5.0.6 on 2024-12-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0011_remove_question_link_sheet_custom_order_and_more'),
    ]

    operations = [

    ]
