# Generated by Django 5.0.6 on 2024-11-05 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0011_batch_sheet_batches_enrollmentrequest_batch_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pods', to='practice.batch'),
        ),
    ]
