# Generated by Django 5.2.5 on 2026-03-16 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0011_alter_batch_required_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqquestion',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcq_questions', to='practice.sheet'),
        ),
    ]
