# Generated by Django 5.0.6 on 2024-11-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0012_pod_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='batches/thumbnails/'),
        ),
    ]
