# Generated by Django 5.0.6 on 2024-12-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0012_remove_question_link_sheet_custom_order'),
    ]

    operations = [

    ]
