# Generated by Django 5.2.5 on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0012_alter_mcqquestion_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
