# Generated by Django 5.0.6 on 2024-12-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0013_remove_question_link_sheet_custom_order'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='sheet',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
