# Generated by Django 5.0.6 on 2024-11-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0014_question_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='constraints',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='scenario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
