# Generated by Django 5.0.6 on 2024-12-19 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_administrator_options'),
        ('practice', '0014_remove_question_link_sheet_custom_order_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='sheet',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='accounts.instructor'),
        ),
      
    ]
