# Generated by Django 5.0.6 on 2024-11-05 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_attendance_scrum_meeting_and_more'),
        ('practice', '0015_question_constraints_question_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='accounts.student'),
        ),
    ]
