# Generated by Django 5.0.6 on 2024-12-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0015_remove_question_link_sheet_created_by_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='streak',
            name='current_streak',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
