# Generated by Django 5.0.6 on 2024-11-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0016_question_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='sheets', to='practice.batch'),
        ),
    ]
