# Generated by Django 5.0.6 on 2024-11-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0017_batch_slug_alter_sheet_batches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
