# Generated by Django 5.0.6 on 2025-01-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0017_remove_question_link_sheet_custom_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='explaination',
            field=models.TextField(blank=True, null=True),
        ),
    ]
