# Generated by Django 5.1.5 on 2025-02-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0018_remove_question_link_sheet_custom_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='link',
        ),
        migrations.AddField(
            model_name='sheet',
            name='custom_order',
            field=models.JSONField(default=dict),
        ),
    ]
