# Generated by Django 5.0.6 on 2025-02-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0018_remove_question_link_sheet_custom_order_and_more'),
    ]

    operations = [



    ]
