# Generated by Django 5.0.6 on 2024-11-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0018_alter_batch_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='constraints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
