# Generated by Django 5.0.6 on 2024-11-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0019_alter_question_constraints_alter_sheet_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='driver_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='input_format',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='output_format',
            field=models.TextField(blank=True, null=True),
        ),
    ]
