# Generated by Django 5.0.6 on 2025-02-11 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0019_remove_question_link_batch_required_fields_and_more'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='question',
            name='link',
        ),
        migrations.AddField(
            model_name='batch',
            name='required_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sheet',
            name='custom_order',
            field=models.JSONField(default=dict),
        ),
        
        migrations.CreateModel(
            name='RecommendedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('platform', models.CharField(choices=[('LeetCode', 'LeetCode'), ('HackerRank', 'HackerRank'), ('GeeksForGeeks', 'GeeksForGeeks')], max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommended_questions', to='practice.question')),
            ],
        ),
    ]
