# Generated by Django 5.0.6 on 2025-02-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0020_remove_question_link_batch_required_fields_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivercode',
            old_name='code',
            new_name='complete_driver_code',
        ),
        migrations.AddField(
            model_name='drivercode',
            name='visible_driver_code',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
