# Generated by Django 5.0.6 on 2025-02-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0021_rename_code_drivercode_complete_driver_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='show_complete_driver_code',
            field=models.BooleanField(default=False),
        ),
    ]
