# Generated by Django 5.2.4 on 2025-08-10 07:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('html_template', models.TextField(help_text='HTML with Jinja-style placeholders: {{ student.full_name }}, {{ event.name }}, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(help_text="Short code used in certificate IDs (e.g., 'FLAMES25MERN').", max_length=20, unique=True)),
                ('start_date', models.DateField(help_text='Date when the event starts. Used for certificate validity.')),
                ('end_date', models.DateField(help_text='Date when the event ends. Used for certificate validity.')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(editable=False, help_text='Auto-generated: EVENTCODE + STUDENTPK', max_length=100, unique=True)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('approved', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='accounts.student')),
                ('template_version', models.ForeignKey(help_text='Template used for rendering this certificate.', on_delete=django.db.models.deletion.PROTECT, to='student.certificatetemplate')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='student.event')),
            ],
            options={
                'ordering': ['-issued_date'],
                'indexes': [models.Index(fields=['certificate_id'], name='student_cer_certifi_9d73ad_idx'), models.Index(fields=['approved'], name='student_cer_approve_680813_idx')],
                'unique_together': {('event', 'student')},
            },
        ),
    ]
