# Generated by Django 5.0.6 on 2025-03-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(choices=[('Online', 'Online'), ('Onsite', 'Onsite')], default='Online', max_length=100)),
                ('registration_deadline', models.DateField()),
                ('prize_pool', models.CharField(blank=True, max_length=50, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='hackathon_thumbnails/')),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
