# Generated by Django 5.2.4 on 2025-09-05 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_certificatetemplate_event_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='template_version',
        ),
        migrations.AddField(
            model_name='event',
            name='certificate_template',
            field=models.ForeignKey(blank=True, help_text='Template used for certificates issued for this event. If not set, uses default template.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.certificatetemplate'),
        ),
    ]
