# Generated by Django 5.0.6 on 2025-03-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_teaminvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonteam',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
