# Generated by Django 5.0.6 on 2025-03-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresettoken'),
        ('student', '0005_alter_teaminvite_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teaminvite',
            unique_together={('team', 'student', 'status')},
        ),
    ]
