# Generated by Django 5.0.6 on 2025-05-31 05:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresettoken'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('student', '0006_alter_teaminvite_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('assignment_type', models.CharField(choices=[('Coding', 'Coding'), ('Text', 'Text'), ('File', 'File'), ('Image', 'Image'), ('Link', 'Link')], db_index=True, max_length=10)),
                ('due_date', models.DateTimeField(db_index=True)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], db_index=True, default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructions', models.TextField(blank=True, help_text='Detailed instructions for students')),
                ('allow_late_submission', models.BooleanField(default=False)),
                ('late_penalty_per_day', models.DecimalField(decimal_places=2, default=0, help_text='Percentage penalty per day (0-100)', max_digits=5)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(blank=True)),
                ('submission_file', models.FileField(blank=True, help_text='Allowed formats: PDF, DOC, DOCX, ZIP, TXT, PY, JS, HTML, CSS', upload_to='assignments/files/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'zip', 'txt', 'py', 'js', 'html', 'css'])])),
                ('submission_image', models.ImageField(blank=True, help_text='Allowed formats: JPG, JPEG, PNG, GIF, WEBP', upload_to='assignments/images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('submission_code', models.TextField(blank=True)),
                ('submission_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20)),
                ('score', models.PositiveIntegerField(blank=True, help_text="Score out of assignment's max_score", null=True)),
                ('feedback', models.TextField(blank=True, help_text='Instructor feedback')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('extra_info', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='student.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Assignment Submission',
                'verbose_name_plural': 'Assignment Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('thumbnail', models.ImageField(blank=True, help_text='Course thumbnail image', null=True, upload_to='course_images/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.instructor')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['content_type', 'object_id'], name='student_ass_content_20ea42_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date', 'status'], name='student_ass_due_dat_79f4af_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['status', 'submitted_at'], name='student_ass_status_cf1b9a_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'status'], name='student_ass_assignm_bfa2ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
    ]
