# Generated by Django 5.0.6 on 2025-05-31 07:02

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_assignment_assignmentsubmission_course_and_more'),
    ]

    operations = [
        
    ]
