# Generated by Django 5.2.5 on 2026-03-08 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_course_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='status',
            new_name='registration_status',
        ),
    ]
