# Generated by Django 5.2.5 on 2026-03-08 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_rename_status_course_registration_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='registration_status',
        ),
    ]
