# Generated by Django 5.2.5 on 2026-03-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_remove_course_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sheet_order',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
