# Generated by Django 5.2.5 on 2026-03-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0009_batch_sheet_order'),
        ('student', '0011_course_sheet_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesheet',
            name='coding_questions',
            field=models.ManyToManyField(blank=True, related_name='course_sheets', to='practice.question'),
        ),
        migrations.AddField(
            model_name='coursesheet',
            name='mcq_questions',
            field=models.ManyToManyField(blank=True, related_name='course_sheets', to='practice.mcqquestion'),
        ),
    ]
