# Generated by Django 5.0.6 on 2025-05-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_assignment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default="2025-05-31 08:03"),
            preserve_default=False,
        ),
    ]
