# Generated by Django 5.2.5 on 2026-04-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0013_alter_streak_current_streak_default"),
        ("student", "0012_coursesheet_coding_questions_and_more"),
    ]

    operations = [
        
    ]
