# Generated by Django 5.0.6 on 2025-05-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_assignment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('Code', 'Code'), ('Text', 'Text'), ('File', 'File'), ('Image', 'Image'), ('Link', 'Link')], db_index=True, max_length=10),
        ),
    ]
