# Generated by Django 5.2.5 on 2026-04-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0013_alter_streak_current_streak_default'),
        ('student', '0013_coursesheet_coding_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesheet',
            name='coding_questions',
            field=models.ManyToManyField(blank=True, related_name='course_sheets', to='practice.question'),
        ),
        migrations.AddField(
            model_name='coursesheet',
            name='mcq_questions',
            field=models.ManyToManyField(blank=True, related_name='course_sheets', to='practice.mcqquestion'),
        ),
    ]
