# Generated by Django 5.2.5 on 2026-04-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_certificate_system_v2'),
        ('student', '0014_coursesheet_coding_questions_and_more'),
    ]

    operations = [
    ]
