# Generated by Django 5.0.6 on 2024-11-05 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_assignmentsubmission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='assignment',
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='course',
        ),
        migrations.RemoveField(
            model_name='session',
            name='course',
        ),
        migrations.RemoveField(
            model_name='session',
            name='instructor',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='AssignmentSubmission',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
