# Generated by Django 5.1.5 on 2025-06-06 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresettoken'),
        ('student', '0017_courseregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_sheets/thumbnails/')),
                ('custom_order', models.JSONField(default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('course', models.ManyToManyField(blank=True, related_name='course_sheets', to='student.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_sheets', to='accounts.instructor')),
            ],
            options={
                'verbose_name': 'Course Sheet',
                'verbose_name_plural': 'Course Sheets',
            },
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='course_sheets',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='student.coursesheet'),
        ),
    ]
