# Generated by Django 5.1.5 on 2025-06-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_remove_assignmentsubmission_course_sheets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='is_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
