# Generated by Django 5.1.5 on 2025-06-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_remove_assignmentsubmission_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
