# Generated by Django 5.1.5 on 2025-06-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_alter_assignment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='tutorial_link',
            field=models.URLField(blank=True, help_text='Link to the tutorial video', null=True),
        ),
    ]
