# Generated by Django 5.1.5 on 2025-06-08 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_assignment_evaluation_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='downloadable_file',
            field=models.FileField(blank=True, help_text='Allowed formats: PDF, DOC, DOCX, ZIP, TXT, PY, JS, HTML, CSS', null=True, upload_to='assignments/files/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'zip', 'txt', 'py', 'js', 'html', 'css'])]),
        ),
    ]
