# Generated by Django 5.1.5 on 2025-06-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_alter_assignment_evaluation_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='downloadable_file',
            field=models.FileField(blank=True, help_text='Allowed formats: PDF, DOC, DOCX, ZIP, TXT, PY, JS, HTML, CSS', null=True, upload_to='assignments/files/%Y/%m/'),
        ),
    ]
